# Generated by Django 6.0.3 on 2026-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
